import { resolve } from 'path'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import externalGlobals from 'rollup-plugin-external-globals'

const componentName = process.env.COMPONENT_NAME

export default defineConfig({
  plugins: [
    vue(),
    externalGlobals({
      vue: 'Vue'
    })
  ], // to process SFC
  build: {
    lib: {
      entry: resolve(__dirname, `src/components/${componentName}.vue`),
      name: componentName,
      formats: ['umd'], // adding 'umd' requires globals set to every external module
      fileName: (_, name) => `${name}.js`
    },
    rollupOptions: {
      // external modules won't be bundled into your library
      external: ['vue'], // not every external has a global
      output: {
        // disable warning on src/index.ts using both default and named export
        exports: 'named',
        // Provide global variables to use in the UMD build
        // for externalized deps (not useful if 'umd' is not in lib.formats)
        globals: {
          vue: 'Vue'
        }
      }
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
    outDir: 'dist-umd'
  }
})
